version: "3.4"

services:
  app:
    build: .
    container_name: flask-mongo-app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - 5000:5000
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: flask-mongo-db
    restart: always
    hostname: test_mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: animal_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: password
  #   depends_on:
  #     - mongodb

  # redis:
  #   image: redis:6.2-alpine
  #   container_name: flask-mongo-redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

volumes:
  mongodb_data:
# docker stop $(docker ps | grep flask-mongo- | awk '{print $1}')
